강원대 Android 6주차과제 이아림 STEP1
kakao-tech-campus-2nd-step2/android-map-notification pull request #37
Opened 2024-07-30 17:06 UTC by arieum

🙋‍♀️`이슈` Firebase 게시가 느린건지 로직문제인지 모르겠습니다!
앱 삭제하고 설치 직후의 Remote_Config 값이 ON_SERVICE, ON_PAUSE 일때 각각 모두 잘 작동합니다
그런데 앱을 삭제하지 않은 채로 기존의 앱으로 remote_config 값을 ON_SERVICE와 ON_PAUSE 업데이트를 변경할 때면 두 번 정도 재실행해야 원하는 로직대로 작동하는 문제가 있습니다.

### 설치직후 ON_SERVICE

https://github.com/user-attachments/assets/1fd67e80-759c-4178-98f6-dfe29921ac3d

### 설치직후 ON_PAUSE

https://github.com/user-attachments/assets/7bdbc580-74a6-4f57-b13a-1bf093bcab01

### ⚠️재설치없이 ON_SERVICE -> ON_PAUSE 값 변동시 ⚠️

https://github.com/user-attachments/assets/ae2f54c6-8df2-47a9-b527-ab043b87ac38

2024-07-31 06:38 UTC, arieum commented
### 🙋‍♀️해결 이후 실행영상

https://github.com/user-attachments/assets/45b04c7e-371b-4cd2-9801-ceaa24c527f8

2024-08-02 11:05 UTC, mkSpace requested changes
.gitignore 파일의 충돌해결이 안된거 같은데 확인해주세요.

아직 코루틴 사용하는 부분에 어색한 부분이 보이네요.

리뷰 남겨드리니 의견 남겨주세요 ~

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/data/db/PlaceDbHelper.kt
> +class PlaceDbHelper(context: Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {
이건 어디서 쓰이나요?

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/data/remote/api/RetrofitClient.kt
> +        .build()
Retrofit은 NetworkModule에서 주입해주고 있지 않나요?

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/data/db/entity/Place.kt
> +    @DrawableRes val img: Int,
DrawableRes id를 넣으면 어떤 부작용이 있을지 생각해보셨나요?

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/repository/LogRepository.kt
> +        }
왜 runBlocking을 쓰셨죠?

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/repository/LogRepository.kt
> +        CoroutineScope(Dispatchers.IO).launch {
이 코루틴 내부 실행들이 매우 오래 걸릴 때 이 코루틴은 언제 종료가 될까요?

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/repository/MapRepository.kt
> +    private val sharedPreferences = application.getSharedPreferences("LastLocation", Context.MODE_PRIVATE)
SharedPreferences는 PreferencesModule에서 주입하고 있지 않나요?

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/repository/PlaceRepository.kt
> +        val apiKey = "KakaoAK " + BuildConfig.KAKAO_REST_API_KEY
KakaoAK는 Consistance로 분리해주세요!

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/repository/RemoteConfigManager.kt
> +    suspend fun fetchAndActivateConfig(): Boolean = suspendCoroutine { continuation ->
suspendCoroutine은 어떤 코루틴인가요?

2024-08-02 11:05 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/repository/WelcomeRepository.kt
> +class WelcomeRepository {
안쓰는거면 지워주세요!

2024-08-02 11:25 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/data/db/PlaceDbHelper.kt
> +class PlaceDbHelper(context: Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {
엇.. 잠시만요.. 저장소 불러올때 잘못 불러온 것 같습니다.... 제  local에는 더이상 sqlite 관련 파일이 없는데ㅠㅠ😢 다시 확인하고 답장 드리겠습니다!

2024-08-02 11:27 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/data/remote/api/RetrofitClient.kt
> +        .build()
뭔가 잘못됐ㄴ어요 ㅠㅠㅠㅠㅠㅠ 이건 음모입니다 ㅠㅠㅠ

2024-08-02 13:04 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/data/db/PlaceDbHelper.kt
> +class PlaceDbHelper(context: Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {
역시나... 뭔가 잘못됐다면 `컴퓨터와 git은 아무 잘못이 없다. 내 잘못이다!`라는 사실을 다시 한번 깨달았습니다.. room으로 바꾼 이후로는 이 파일들을 삭제했어야했는데 지금껏 삭제를 안한채로 계속 불러와서 잔재하고 있었습니다 - ⭐
결론은.. 삭제했습니다 ★ !!

2024-08-02 13:05 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/data/remote/api/RetrofitClient.kt
> +        .build()
이제 필요없는 파일들은 모두 삭제했습니다 - !

2024-08-02 13:20 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/repository/MapRepository.kt
> +    private val sharedPreferences = application.getSharedPreferences("LastLocation", Context.MODE_PRIVATE)
- `class MapRepository @Inject constructor( private val sharedPreferences: SharedPreferences )` 주입완료!
- `repositoryModule_provideMapRepository` 파라미터 수정 !

2024-08-02 13:39 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/repository/WelcomeRepository.kt
> +class WelcomeRepository {
step1에서 안쓰이면 add하지 말았어야 하는데 ㅠ죄송합니다ㅠ step2에선 쓰입니다..!

2024-08-02 14:35 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/data/db/entity/Place.kt
> +    @DrawableRes val img: Int,
https://stackoverflow.com/questions/6804053/understand-the-r-class-in-android
빌드될 때 리소스 ID가 동적으로 생성돼서인가요..?!🤔 흠.. 근데 설치한 기기에서는 id가 고정되지 않나용..?

💁‍♀️ place의 img 속성을 없애고 xml에서 고정된 이미지를 사용하도록 수정했습니다!
그리고 수정한 코드로 실행시키기 위해 앱에서 캐시삭제 + 데이터삭제 + 재설치했습니다! 그런데.. 이후로 appdatabase json 파일내용이 자동으로 수정되었습니다.. 그래서 step2로 commit 올려야 할 것 같습니다 (현재 제 local은 step2 브랜치 작업상태입니다)!

2024-08-03 06:00 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/repository/RemoteConfigManager.kt
> +    suspend fun fetchAndActivateConfig(): Boolean = suspendCoroutine { continuation ->
코루틴없이 원하는 대로 코드가 흘러가려면 콜백메서드를 써야하는데 콜백메서드는 코드를 거슬러 올라가야 하는 점에서 가독성이 떨어진다고 생각들었습니다 그래서 구글링하다가 이 자료를 보고 저랑 비슷한 상황이라서 쓰게 됐습니다 🥲
https://velog.io/@minlove2013/Kotlin-%EB%B9%84%EB%8F%99%EA%B8%B0-%EB%B0%A9%EC%8B%9D%EC%9C%BC%EB%A1%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%EC%B2%98%EB%A6%AC%ED%95%A0-%EB%95%8C-%EC%9B%90%ED%95%98%EB%8A%94-%EA%B0%92%EC%9D%B4-%EB%82%98%EC%98%A4%EC%A7%88-%EC%95%8A%EC%95%84-SuspendCoroutine-%EC%9D%B4%EC%9A%A9

2024-08-03 06:01 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/repository/RemoteConfigManager.kt
> +    suspend fun fetchAndActivateConfig(): Boolean = suspendCoroutine { continuation ->
콜백메서드나 코루틴없이는 원하는 때에 remoteconfig 값을 제대로 가져오지 않았습니다..!

2024-08-03 06:10 UTC, mkSpace commented
변경 내용들은 Step2에서 확인할게요 리베이스 해주세요 ~

2024-08-03 06:10 UTC, merged

2024-08-03 06:16 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/repository/LogRepository.kt
> +        }
sqlite에서 room으로 바꾼 이후로부터 (db를 처리하기도전에 loglist를 반환하려한 것같습니다) 이전 값을 아예 불러오지도 못하고 강제종료되었습니다..! 그래서 runblocking을 쓰게 됐는데..! 지금껏 위험성을 잘 모르고 헬레렐 실행된다!  하고 썼는데 멘토님 리뷰보고 찾아보니
![image](https://github.com/user-attachments/assets/7dff72e3-39b7-4b25-9a66-ab65bc6780b8)
.. 이런 위험성때문에 .. 다른걸로 대체하는게 좋을까요??

2024-08-03 06:32 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/repository/RemoteConfigManager.kt
> +    suspend fun fetchAndActivateConfig(): Boolean = suspendCoroutine { continuation ->
다른 적절한 코루틴로 바꿔보겠습니다!!