[강원대 안드로이드 주민철] 6주차 과제 스텝1
kakao-tech-campus-2nd-step2/android-map-notification pull request #57
Opened 2024-08-01 05:45 UTC by joominchul

# 어려웠던 점
- 스플래시 화면을 구현하는 로직이 비즈니스 로직 같아, 따로 뷰모델을 만들어 옮기려 했는데, 실패했습니다. serviceMessage 값을 설정하기 위해 문자열을 리턴하게 하였는데, addOnCompleteListener 안에서는 지역 변수에 값이 할당이 안 돼서 리턴 값이 제대로 나오지 않았습니다. 이 부분만 해결되면 뷰모델로 로직을 옮길 수 있을 것 같습니다.

2024-08-02 11:23 UTC, mkSpace requested changes
지금 다음 step을 진행하실게 아니고 Repository Pattern을 먼저 적용해주세요.

ViewModel의 하는역할이 너무 많습니다.

그리고 RetrofitData 등의 data layer의 객체들이 url 패키지 안에 있는데 어떤 의미인가요?

2024-08-02 11:23 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +		model.documentClickedDone()
이건 왜 여기서 호출하는거죠?

2024-08-02 11:23 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/view/SearchFragment.kt
> +		}
여기서 호출하시는게 초기 데이터 불러오기 위함이면 차라리 ViewModel의 init 단에서 호출해주세요
굳이 순서가 생길 이유는 없을 것 같네요

2024-08-02 11:23 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/view/SearchFragment.kt
> +			searchBinding.invalidateAll()
invalidateAll 하는 이유가 있나요?

2024-08-02 11:23 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/view/SearchFragment.kt
> +			model.documentListObserved(documents, searchBinding, documentAdapter)
model에 Binding과 Adapter를 왜 넘기나요?
순환이 생긴거 같은데 다시 구상해 보세요

2024-08-02 11:23 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/viewModel/MainViewModel.kt
> +		}
뷰와 관련된 내용이 있어선 안됩니다.
뷰와 관련된 파라미터를 넘겨 받아서도 안되구요.
데이터를 방출하고 View에서 바인딩해주세요

2024-08-02 14:19 UTC, joominchul commented
> 지금 다음 step을 진행하실게 아니고 Repository Pattern을 먼저 적용해주세요.
> 
> ViewModel의 하는역할이 너무 많습니다.
> 
> 그리고 RetrofitData 등의 data layer의 객체들이 url 패키지 안에 있는데 어떤 의미인가요?

레포지토리 패턴 열심히 공부하겠습니다. 그리고 url 이란 명칭이 아무래도 부적절한 것 같아 remote로 바꾸겠습니다. 또한 dto 명칭도 data로 바꾸는 게 좋겠단 생각이 듭니다...

2024-08-02 15:44 UTC, joominchul commented
> > 지금 다음 step을 진행하실게 아니고 Repository Pattern을 먼저 적용해주세요.
> > ViewModel의 하는역할이 너무 많습니다.
> > 그리고 RetrofitData 등의 data layer의 객체들이 url 패키지 안에 있는데 어떤 의미인가요?
> 
> 레포지토리 패턴 열심히 공부하겠습니다. 그리고 url 이란 명칭이 아무래도 부적절한 것 같아 remote로 바꾸겠습니다. 또한 dto 명칭도 data로 바꾸는 게 좋겠단 생각이 듭니다...

2024-08-03 04:04 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/viewModel/MainViewModel.kt
> +		}
코치님께서 위 판단하는 로직도 뷰모델에 있는 것이 베스트라고 [하셔서](https://github.com/kakao-tech-campus-2nd-step2/android-map-refactoring/pull/82#discussion_r1694289437) 옮겼는데, 제가 잘 못 이해한 것 같습니다. 정확히 어떻게 하는 것이 좋을까요? 감이 안 잡힙니다 ㅠㅠ

2024-08-03 04:09 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +		model.documentClickedDone()
`model.documentClickedDone()`를 말씀하시는 건가요? 이 코드는 뷰모델 내의 _documentClicked MutableLiveData 값을 false로 설정하는 코드입니다. 이후 결과값을 클릭하면 값이 true로 바뀌면서 액티비티가 지도에 마커와 바텀시트를 설정합니다.

2024-08-03 04:14 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/view/SearchFragment.kt
> +		}
[수정](https://github.com/kakao-tech-campus-2nd-step2/android-map-notification/pull/57/commits/f2cd362154050b9ed85d68538dc71af7fa11a28e)했습니다.

2024-08-03 04:17 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/view/SearchFragment.kt
> +			searchBinding.invalidateAll()
데이터바인딩된 변수들을 모두 갱신해 주는 함수인데, 생각해보니 xml에 바인딩된 변수가 없었네요...;;

알려주셔서 감사합니다! 삭제했습니다.

2024-08-03 04:19 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/view/SearchFragment.kt
> +			model.documentListObserved(documents, searchBinding, documentAdapter)
다시 관련된 뷰모델 로직들을 프래그먼트로 옮기는 게 좋을까요?

2024-08-03 06:14 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/viewModel/MainViewModel.kt
> +		}
아 이전에 말씀드린거는 판단하는 것을 ViewModel로 미루라는 말씀이었어요.
그니까 여기서는 query.isEmpty에 해당하는 부분은 ViewModel에서 부터 내려와야 한다는거죠.
여기서는 searchResult를 보여주냐 마냐의 문제니까 LiveData로 showSearchResult 등으로 만들어서 바인딩해주면 되겠네요.
뷰 세팅 관련 (여기서는 VISIBILITY 설정)들은 모두 뷰에서 해줘야 합니다.

2024-08-03 06:15 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/view/SearchFragment.kt
> +			model.documentListObserved(documents, searchBinding, documentAdapter)
documentListObserved 에서 하는걸 그냥 뷰에서 하면 되는거죠

2024-08-03 06:20 UTC, mkSpace requested changes

2024-08-03 06:20 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/repository/MapPositionRepository.kt
> +	}
LiveData는 Repository 단에서는 쓰면 안됩니다.
코루틴 배우셨으니 코루틴으로 변환해보세요!

2024-08-03 06:20 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/data/remote/RetrofitData.kt
> +	}
여기도 코루틴으로 해결해보세요

2024-08-03 06:20 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/data/remote/RetrofitData.kt
>  	private val _documents = MutableLiveData<List<Document>>()
흠.. 이것도 사실 분리하는게(역할에 맞게 축소) 좋습니다. PlaceRemoteDataSource 정도로 만들고 Repository에서 호출해서 사용하는 걸로 변경해주세요.

2024-08-03 06:36 UTC, mkSpace commented
https://developer.android.com/codelabs/basic-android-kotlin-training-repository-pattern?hl=ko#0

코드랩 링크인데 이걸 참고해보세요

2024-08-03 07:42 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/viewModel/MainViewModel.kt
> +		}
[고쳤습니다!](https://github.com/kakao-tech-campus-2nd-step2/android-map-notification/pull/57/commits/2a436cdc31b97d7558f4903c2156a8bc100ad6dc)

2024-08-03 08:25 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/repository/MapPositionRepository.kt
> +	}
코루틴으로 변환하란 말씀은 Flow를 사용하란 뜻이죠? 

한번 [시도](https://github.com/kakao-tech-campus-2nd-step2/android-map-notification/pull/57/commits/21964da7661da32b88fc5de8c1be481269da5e05)해 보았습니다. 확인해 주세요.

2024-08-03 08:49 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/data/remote/RetrofitData.kt
> +	}
[변경](https://github.com/kakao-tech-campus-2nd-step2/android-map-notification/pull/57/commits/3c460043537798740c50d2145e693fdc66ec1f26)해 보았습니다.

2024-08-03 12:16 UTC, joominchul commented on app/src/main/java/campus/tech/kakao/map/data/remote/RetrofitData.kt
>  	private val _documents = MutableLiveData<List<Document>>()
음...  일단 [코드](https://github.com/kakao-tech-campus-2nd-step2/android-map-notification/pull/57/commits/f6a8edac1126a57e3527d487f0f406fe6a829d5b)를 한번 짜 보았습니다. 확인 부탁드려요!

2024-08-04 12:33 UTC, mkSpace commented
우선 머지 드리니 step2 리베이스 부탁드려요

2024-08-04 12:33 UTC, merged